/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Reto;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import net.bytebuddy.build.Plugin.Engine.Dispatcher.ForParallelTransformation.WithThrowawayExecutorService;

import static org.junit.Assert.*;

public class AppTest {
    
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void Registration () throws InterruptedException {
        System.setProperty("webdriver.chrome.driver", "../drive/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.get("http://automationpractice.com/index.php");
        driver.manage().window().maximize();
        driver.findElement(By.className("login")).click();
        // change mail for each run
        driver.findElement(By.id("email_create")).sendKeys("5201ffera@gmail.com");
        driver.findElement(By.id("SubmitCreate")).click();
        //wait for next page to load
        Thread.sleep(3000);
        driver.findElement(By.id("id_gender1")).click();   
        driver.findElement(By.id("customer_firstname")).sendKeys("Marco");
        driver.findElement(By.id("customer_lastname")).sendKeys("Polo");
        driver.findElement(By.id("passwd")).sendKeys("F54654B");   
        //Selectors Date of Birth
        WebElement eleDay = driver.findElement(By.name("days"));
        Select selectDay = new Select(eleDay);
        selectDay.selectByValue("30"); // 1 to 31
        WebElement eleMonth = driver.findElement(By.name("months"));
        Select selectMonth = new Select(eleMonth);
        selectMonth.selectByValue("8"); // 1 to 12
        WebElement eleYear = driver.findElement(By.name("years"));
        Select selectYear = new Select(eleYear);
        selectYear.selectByValue("1995"); // 1900 to 2021
        driver.findElement(By.id("company")).sendKeys("FB.SAS");
        driver.findElement(By.id("address1")).sendKeys("Cl 7 3-20");
        driver.findElement(By.id("address2")).sendKeys("Local 2");
        driver.findElement(By.id("city")).sendKeys("Bogotá");
        //Selector state 
        WebElement eleState = driver.findElement(By.name("id_state"));
        Select selectState = new Select(eleState);
        selectState.selectByValue("35"); // 1 to 50 postcode
        driver.findElement(By.id("postcode")).sendKeys("10100"); //maximum 5 digits
        //Selector country 
        WebElement eleCountry = driver.findElement(By.name("id_country"));
        Select selectCountry = new Select(eleCountry);
        selectCountry.selectByValue("21"); // 21
        driver.findElement(By.id("other")).sendKeys("Other Number 333333");
        driver.findElement(By.id("phone")).sendKeys("222222");
        driver.findElement(By.id("phone_mobile")).sendKeys("3132519318");
        driver.findElement(By.id("alias")).clear();
        driver.findElement(By.id("alias")).sendKeys("Home"); 
        driver.findElement(By.id("submitAccount")).click();
    }

    @Test public void Login () throws InterruptedException {
        System.setProperty("webdriver.chrome.driver", "../drive/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.get("http://automationpractice.com/index.php?controller=authentication&back=my-account");
        driver.manage().window().maximize();
        driver.findElement(By.id("email")).sendKeys("pipe_brelinz@gmail.com");
        driver.findElement(By.id("passwd")).sendKeys("FelipeB");
        driver.findElement(By.id("SubmitLogin")).click();
        Thread.sleep(3000);
        driver.findElement(By.className("icon-user")).click();
        driver.findElement(By.id("id_gender2")).click();   
        driver.findElement(By.id("firstname")).clear();
        driver.findElement(By.id("firstname")).sendKeys("Brayan");
        driver.findElement(By.id("lastname")).clear();
        driver.findElement(By.id("lastname")).sendKeys("Núñez");
        WebElement eleMonth = driver.findElement(By.name("months"));
        Select selectMonth = new Select(eleMonth);
        selectMonth.selectByValue("12"); // 1 to 12
        driver.findElement(By.id("old_passwd")).sendKeys("FelipeB");
        driver.findElement(By.name("submitIdentity")).click();
    }

    @Test public void Contact() {
        System.setProperty("webdriver.chrome.driver", "../drive/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("http://automationpractice.com/index.php?controller=contact");
        WebElement eleSubHeading = driver.findElement(By.name("id_contact"));
        Select selectSubHeading = new Select(eleSubHeading);
        selectSubHeading.selectByValue("2"); // 0, 1 or 2
        driver.findElement(By.id("email")).sendKeys("pruef@gmail.com");
        driver.findElement(By.id("id_order")).sendKeys("It's order");
        driver.findElement(By.id("message")).sendKeys("It's message");
        driver.findElement(By.id("submitMessage")).click();
    }

    @Test public void ContactLogin () throws InterruptedException {
        System.setProperty("webdriver.chrome.driver", "../drive/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("http://automationpractice.com/index.php?controller=authentication&back=my-account");
        driver.findElement(By.id("email")).sendKeys("pipe_brelinz@gmail.com");
        driver.findElement(By.id("passwd")).sendKeys("FelipeB");
        driver.findElement(By.id("SubmitLogin")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("contact-link")).click();
        Thread.sleep(3000);
        WebElement eleSubHeading = driver.findElement(By.name("id_contact"));
        Select selectSubHeading = new Select(eleSubHeading);
        selectSubHeading.selectByValue("1"); // 0, 1 or 2
        // assigned value for each completed order
        WebElement eleOrder = driver.findElement(By.name("id_order"));
        Select selectOrder = new Select(eleOrder);
        selectOrder.selectByValue("375334"); // value 375334
        WebElement eleProduct = driver.findElement(By.name("id_product"));
        Select selectProduct = new Select(eleProduct);
        selectProduct.selectByValue("3"); // o, 2 or 3
        driver.findElement(By.id("message")).sendKeys("It's message");
        driver.findElement(By.id("submitMessage")).click();
    }

    @Test public void Search() throws InterruptedException {
        System.setProperty("webdriver.chrome.driver", "../drive/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("http://automationpractice.com/index.php");
        driver.findElement(By.id("search_query_top")).sendKeys("Dress");
        driver.findElement(By.name("submit_search")).click();
        Thread.sleep(5000);
        driver.findElement(By.id("search_query_top")).clear();
        driver.findElement(By.id("search_query_top")).sendKeys("1598xyz");
        driver.findElement(By.name("submit_search")).click();
        Thread.sleep(5000);
        driver.findElement(By.id("search_query_top")).clear();
        driver.findElement(By.id("search_query_top")).sendKeys("Dres");
        driver.findElement(By.name("submit_search")).click();
    }
}
